title: Joe Ambrosio Yoga
apiBaseUrl: https://ga09zolgt2.execute-api.eu-west-3.amazonaws.com
news: "Les cours réguliers sont suspendus pour le moment, n'hésitez pas à me contacter pour des cours particuliers !"
