title: Joe Ambrosio Yoga
apiBaseUrl: https://ga09zolgt2.execute-api.eu-west-3.amazonaws.com
news: Pas de cours exceptionnellement la semaine du 16 au 22 novembre mais des cours de découverte gratuits sont disponibles à partir du 23 novembre.
